server:
  port: 9000

eureka:
  instance:
    appname: API-GATEWAY
    instanceId: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
      

spring:
  application:
    name: API-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: hello-world
          uri: lb://HELLO-WORLD/
          predicates:
            - Path=/api/hello-world/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: /hello-world-fallback
        - id: my-authentication-service
          uri: lb://MY-AUTHENTICATION-SERVICE/
          predicates:
            - Path=/api/authenticate/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: /authentication-fallback
        - id: class-scheduler-teacher
          uri: lb://CLASS-SCHEDULER-TEACHER/
          predicates:
            - Path=/api/scheduler-teacher/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: /scheduler-teacher-fallback
        - id: class-scheduler-student
          uri: lb://CLASS-SCHEDULER-STUDENT/
          predicates:
            - Path=/api/scheduler-student/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: /scheduler-student-fallback

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,info,health

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 3s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10


resilience4j.retry:
  configs:
    default:
      max-attempts: 3
      waitDuration: 100