server:
  port: 9000

eureka:
  instance:
    appname: API-GATEWAY
    instanceId: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: API-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: hello-world
          uri: lb://HELLO-WORLD/
          predicates:
            - Path=/api/hello-world/**

