
spring:
  application:
    name: API-gateway
  cloud:
    gateway:
      routes:
      - id: hello-world
        uri: lb://HELLO-WORLD
        predicates:
        - Path=/hello-world/**

server:
  port: 9000

eureka:
  instance:
    appname: API-GATEWAY
  client:
    service-url.defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
